# This file is kept for potential future task configurations
# Currently, the main task is defined directly in crew.py as symptom_interview_task

# Future task configurations can be added here if needed

# Main task configuration - actual implementation is in crew.py
symptom_interview_task:
  description: "Placeholder - actual task defined in crew.py"
  expected_output: "Symptom interview results"
  agent: communicator
